services:
  database:
    image: postgres:15
    container_name: next_js_simple_api_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=next_js_simple_api_dev
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
